import os
import yaml
import argparse
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent
LOG_DIR = ROOT / "docs/agents/logs"
STATE_DIR = ROOT / "agent_states"

def main():
    parser = argparse.ArgumentParser(description="Agent Log Shifter - The Secretary")
    parser.add_argument("task", help="Brief description of the task completed")
    parser.add_argument("--role", default="ENV_ENGINEER", help="Your current role")
    parser.add_argument("--details", help="Detailed list of changes (comma separated)", default="")
    
    args = parser.parse_args()
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%Y-%m-%d %H:%M")

    # 1. Update YAML State
    state_file = STATE_DIR / f"{args.role}_state.yml"
    if state_file.exists():
        with open(state_file, 'r') as f:
            state = yaml.safe_load(f)
        
        if 'history' not in state: state['history'] = []
        state['history'].append({
            'date': date_str,
            'task': args.task
        })
        
        with open(state_file, 'w') as f:
            yaml.dump(state, f, allow_unicode=True, default_flow_style=False)
        print(f"✅ Updated {args.role}_state.yml")

    # 2. Update Log File
    log_file = LOG_DIR / f"{args.role}_agent.log"
    details_block = "\n".join([f"- {d.strip()}" for d in args.details.split(",") if d.strip()])
    
    log_entry = f"""
Date: {time_str}
Task: {args.task}
Role: {args.role}
{details_block if details_block else "- Automatic log entry generated by Log Shifter"}
Verify: pnpm verify = [PENDING]
Status: SUCCESS
"""
    with open(log_file, 'a') as f:
        f.write(log_entry)
    print(f"✅ Appended to {args.role}_agent.log")

if __name__ == "__main__":
    main()
