"""
knowledge_injector.py - Context Package Generator
Superior Meta-Architect+ System

Generates knowledge injection packages for sub-agents.
"""

from pathlib import Path
from typing import Dict, List, Optional
from dataclasses import dataclass
from datetime import datetime, timezone

from graph_query import GraphQuery, GraphNode, ROLE_CATEGORY_MAP


@dataclass
class ContextPackage:
    """Knowledge injection package for a sub-agent"""
    agent_role: str
    generated_at: str
    nodes: List[GraphNode]
    constraints: List[str]
    rules: List[str]
    mcp_tools_enabled: List[str]


class KnowledgeInjector:
    """
    Generates context injection packages from Graph data.
    """
    
    def __init__(self, graph_query: GraphQuery):
        self.gq = graph_query
    
    def generate_package(
        self,
        agent_role: str,
        requirements: List[str],
        mcp_tools: Optional[List[str]] = None
    ) -> ContextPackage:
        """Generate a context package for an agent"""
        
        category = ROLE_CATEGORY_MAP.get(agent_role)
        if not category:
            raise ValueError(f"Unknown role: {agent_role}")
        
        # Query graph
        nodes = self.gq.query_by_category(category, priority_threshold=2)
        filtered = self.gq.filter_by_keywords(nodes, requirements)
        locked = self.gq.get_locked_nodes(category)
        
        # Build constraints
        constraints = [
            f"Identity-locked nodes: {', '.join(locked) if locked else 'None'}",
            "Cannot modify priority=1 nodes without approval",
            "All references must exist in knowledge graph"
        ]
        
        # Build rules
        rules = [
            "All decisions MUST reference documentation from nodes above",
            "If missing info: 'ESCALATION REQUIRED: Missing data for [topic]'",
            "Never invent API signatures or schemas",
            "Query Meta-Architect with: '@meta-architect [question]'",
            "Document all decisions in code comments"
        ]
        
        if mcp_tools is None:
            mcp_tools = ["filesystem", "web_search"]
        
        return ContextPackage(
            agent_role=agent_role,
            generated_at=datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
            nodes=filtered,
            constraints=constraints,
            rules=rules,
            mcp_tools_enabled=mcp_tools
        )
    
    def render_as_markdown(self, package: ContextPackage) -> str:
        """Render package as Markdown for agent injection"""
        
        md = f"""# KNOWLEDGE INJECTION: {package.agent_role.upper()}

## Generated: {package.generated_at}

---

## 📚 DOCUMENTATION ({len(package.nodes)} nodes)

"""
        # Group by priority
        by_priority = {}
        for node in package.nodes:
            by_priority.setdefault(node.priority, []).append(node)
        
        for priority in sorted(by_priority.keys()):
            md += f"### Priority {priority}\n\n"
            for node in by_priority[priority]:
                md += f"#### {node.id}\n"
                md += f"- **Type**: {node.type}\n"
                md += f"- **Category**: {node.sub_category}\n"
                md += f"- **URL**: {node.url}\n\n"
        
        md += "---\n\n## 🚫 CONSTRAINTS\n\n"
        for i, c in enumerate(package.constraints, 1):
            md += f"{i}. {c}\n"
        
        md += "\n---\n\n## 📋 RULES\n\n"
        for i, r in enumerate(package.rules, 1):
            md += f"{i}. {r}\n"
        
        md += "\n---\n\n## 🔧 MCP TOOLS\n\n"
        for tool in package.mcp_tools_enabled:
            md += f"- `{tool}`\n"
        
        md += "\n---\n\n_Auto-generated by Meta-Architect_\n"
        
        return md
    
    def save_package(
        self,
        package: ContextPackage,
        output_dir: str = "./context_packages"
    ) -> Path:
        """Save package to file"""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"{package.agent_role}_{timestamp}.md"
        filepath = output_dir / filename
        
        content = self.render_as_markdown(package)
        filepath.write_text(content, encoding='utf-8')
        
        print(f"[KnowledgeInjector] Saved: {filepath}")
        return filepath


def generate_context_package(
    agent_role: str,
    nodes: List[GraphNode],
    locked_nodes: List[str],
    mcp_tools: List[str]
) -> ContextPackage:
    """Functional interface for workflow use"""
    return ContextPackage(
        agent_role=agent_role,
        generated_at=datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
        nodes=nodes,
        constraints=[
            f"Identity-locked: {', '.join(locked_nodes)}",
            "Cannot modify priority=1 nodes"
        ],
        rules=[
            "Reference documentation from nodes",
            "Escalate missing info",
            "Never invent API signatures"
        ],
        mcp_tools_enabled=mcp_tools
    )


if __name__ == "__main__":
    from graph_query import GraphQuery
    
    print("\n=== Testing Knowledge Injector ===")
    
    gq = GraphQuery("knowledge_graph.json")
    ki = KnowledgeInjector(gq)
    
    package = ki.generate_package(
        agent_role="frontend_specialist",
        requirements=["react", "nextjs", "tailwind"],
        mcp_tools=["filesystem", "playwright"]
    )
    
    print(f"Generated package with {len(package.nodes)} nodes")
    
    path = ki.save_package(package)
    print(f"Saved to: {path}")
