#!/bin/bash
# Setup pre-commit hook for BrainBox verification

HOOK_PATH=".git/hooks/pre-commit"

echo "🔧 Installing BrainBox verification pre-commit hook..."

cat > "$HOOK_PATH" << 'EOF'
#!/bin/bash
# BrainBox Pre-Commit Verification Hook
# Auto-generated by setup-verification-hook.sh

echo "🔍 Running BrainBox schema verification..."

python3 scripts/verification.py

if [ $? -ne 0 ]; then
  echo ""
  echo "❌ Verification failed. Commit blocked."
  echo "   Fix violations above or bypass with: git commit --no-verify"
  exit 1
fi

echo "✅ Verification passed. Proceeding with commit..."
exit 0
EOF

chmod +x "$HOOK_PATH"

echo "✅ Pre-commit hook installed at $HOOK_PATH"
echo ""
echo "To test: make a change and run 'git commit'"
echo "To bypass: use 'git commit --no-verify' (not recommended)"
